### ISSUE TITLE
OSX-KVM-installer

### ISSUE THREAD

**Issue by hiroshclan** [relf108/OSX-KVM-installer#3]
After i follow your Post Installation guide and finish all setup proces, i can't find the OSX-KVM-installer to run osx_kvm_runner in OSX-KVM-runner directory
To run new macOS installation, i choose catalina number 13 in fetch list, and succesed follow all the instalation guide

**Comment by relf108** [comment]
It looks like the virt machine manager setup can sometimes throw an exception if the environment is a little atypical and therefore prevent the code from reaching the runner setup. I've added a try catch block around this and the program should now continue if it fails to add the vm to the manager as this is not a big deal.

In the short term, you can download the runner directly from
https://github.com/relf108/OSX-KVM-runner/releases/download/beta-2/OSX-KVM-runner

You may need to make it executable after downloading with
```
chmod +x OSX-KVM-runner
```
then run it with
```
./OSX-KVM-runner
```
Thanks so much for getting involved in the project and let me know if you encounter any more issues.

**Comment by hiroshclan** [comment]
me too :) 
but now i faced new problem
this is the ss of the error
![Screenshot from 2021-01-14 11-56-30](https://user-images.githubusercontent.com/44330930/104546814-98c71d80-565f-11eb-811e-4e36048814ce.png)

**Comment by relf108** [comment]
Run without sudo.
Virsh networking behaves very differently depending on its permissions.

**Comment by hiroshclan** [comment]
it same , run without sudo
![Screenshot from 2021-01-14 13-39-06](https://user-images.githubusercontent.com/44330930/104553879-fa8e8400-566d-11eb-99a5-3e5bacf2ca28.png)

**Comment by relf108** [comment]
In that case re-run the installer but skip the post installation steps (close the vm when it pops up) and then run the runner again. The installer has code in it that should fix networking issues and I'll update the runner to do the same.
Thanks again for bearing with me through this. It's been an enormous help in working the kinks out of the code :)

EDIT: just finished updating the runner. Try extracting this and running it without sudo again `./osx_kvm_runner`. You may need to `chmod +x` it again
[osx_kvm_runner.zip](https://github.com/relf108/OSX-KVM-installer/files/5812833/osx_kvm_runner.zip)

**Comment by hiroshclan** [comment]
thank you for your hard work, this can't be such an easier without your script, now i must dealing with this damn slow connection and quota limitation from my provider, i will let you know after this runner process done, thank you so much :)

**Comment by hiroshclan** [comment]
i'm sorry, but it still error on tap0
![Screenshot from 2021-01-14 14-49-18](https://user-images.githubusercontent.com/44330930/104560018-dafc5900-5677-11eb-8ae2-dac79886cf9a.png)

**Comment by relf108** [comment]
Could you show me the output of running this command
```sudo ip tuntap add dev tap0 mode tap```
followed by running the runner again.

**Comment by hiroshclan** [comment]
octl(TUNSETIFF): Device or resource busy

EDIT : after rebooting i run "sudo ip tuntap add dev tap0 mode tap" again, but nothing shows up, and then run the runner, but the error is still same

**Comment by relf108** [comment]
Try these commands for me and see how it goes.
```
cd OSX-KVM-installer/OSX-KVM
sudo ./OpenCore-Boot.sh
```
This behavior is really strange, the code should be dealing with the tap issue as it's quite common and well tested. I'm starting to think the installer failing initially meant the required directories were setup incorrectly. If this doesn't work show me the output and we might need to try a full re-install of the VM.

EDIT: are you using a vpn? In rare cases it can affect the installer when dealing with tap0

**Comment by hiroshclan** [comment]
yes, i'm so sorry,  i think i messed up this time, i dont' have OSX-KVM-installer directory,  when i run this command "wget https://github.com/relf108/OSX-KVM-installer/releases/download/v1.5/osx_kvm_installer" a file with a name "osx_kvm_installer" downloaded in my home directory

![Screenshot from 2021-01-14 15-36-41](https://user-images.githubusercontent.com/44330930/104565339-b9eb3680-567e-11eb-8b7f-e5172352905c.png)

and then i make this file executable with chmod and run the file, after that a folder with a name OSX-KVM created with all it's file in there

![Screenshot from 2021-01-14 15-43-06](https://user-images.githubusercontent.com/44330930/104565721-45fd5e00-567f-11eb-89fe-615feda36702.png)

i finished all mac installation process, but i never find the OSX-KVM-installer directory

**Comment by relf108** [comment]
That is actually my bad, I need to update the doco on github to use the correct executable.
That being said that folder missing is what would have been causing the errors.
From that directory you should now be able to run
```sudo ./OpenCore-Boot.sh```
If that works, try creating the OSX-KVM-installer directory yourself and placing the OSX-KVM directory inside it and I think the runner will begin to work.

**Comment by relf108** [comment]
I've just edited the release executable to use the latest version so the github documentation should be accurate now.

**Comment by relf108** [comment]
Okay so after a little more digging I'm now certain the issue was that you were using an older version of the software which is entirely my fault for forgetting to update the Github release. If what I just suggested doesn't get things going a full re-install using the following command should almost certainly work. Super sorry about the oversight.
```
pub global activate osx_kvm_installer
osx_kvm_installer
```

**Comment by hiroshclan** [comment]
i decide to full re-install, and after instalation process, i've got new problem, the installer resaources were not found
![Screenshot from 2021-01-14 22-07-00](https://user-images.githubusercontent.com/44330930/104610799-ffc3f100-56b6-11eb-8cd0-f418aa8df069.png)

**Comment by relf108** [comment]
Would you be able to send a screenshot of the MacOS DiskUtility so I can see each of your virtual drives?

**Comment by hiroshclan** [comment]
this is the ss
![Screenshot from 2021-01-15 10-25-42](https://user-images.githubusercontent.com/44330930/104677490-151f3680-571c-11eb-8af1-1226dbb259f5.png)

**Comment by relf108** [comment]
This looks a little unusual. I see you have what looks to be two root partitions. This is what I would be expecting to see.
![image](https://user-images.githubusercontent.com/11174524/104678278-2ded1380-573f-11eb-9291-4a167fa6b0e2.png)
Did you delete the OSX-KVM directory and any other directories created by the installer before starting the install process again?
If not, I would suggest doing so as I think the duplicate hard drives are what is confusing the installer. 

EDIT: You may be able to get away with just choosing the re-clone option when OSX-KVM-installer is running if you wanted to try save some time but my first suggestion is probably the safer option

**Comment by hiroshclan** [comment]
i start from begining, delete all the folder and files, then follow your updated guide in github documentation  to full re-install

**Comment by relf108** [comment]
Could you show me the other drive titled Mac

**Comment by relf108** [comment]
I'm currently doing a full reinstall on my machine following the GitHub instructions to try and replicate your issue

EDIT: I'm going to record the post installation steps so we can ensure you're doing the same thing.

**Comment by relf108** [comment]
Are these steps the same as what you did?
https://user-images.githubusercontent.com/11174524/104683212-955c9080-574a-11eb-83fd-6cbbacb35231.mp4

EDIT: One thing I've noticed you've done differently is format your root drive as APFS instead of MAC OS Extended (Journaled). This could definitely be causing the problem.

**Comment by hiroshclan** [comment]
> Could you show me the other drive titled Mac

This is the other drive
![Screenshot from 2021-01-15 11-40-16](https://user-images.githubusercontent.com/44330930/104689337-f0838880-5734-11eb-8de6-7d65a99f9f38.png)
![Screenshot from 2021-01-15 11-40-32](https://user-images.githubusercontent.com/44330930/104689357-f9745a00-5734-11eb-9489-44baacf1405b.png)
![Screenshot from 2021-01-15 11-40-51](https://user-images.githubusercontent.com/44330930/104689377-009b6800-5735-11eb-8916-3a81221e287a.png)

**Comment by hiroshclan** [comment]
> Are these steps the same as what you did?
> https://user-images.githubusercontent.com/11174524/104683212-955c9080-574a-11eb-83fd-6cbbacb35231.mp4
> 
> EDIT: One thing I've noticed you've done differently is format your root drive as APFS instead of MAC OS Extended (Journaled). This could definitely be causing the problem.

yes, what i did is same as in your video, and i leave all the format option in default state

**Comment by relf108** [comment]
I'm really confused as to how we managed to get into a state where you have multiple large drives setup without some custom partitioning, I also followed the instructions that I have listed on this repo and couldn't replicate your circumstances.
Beyond that, I'm not sure why the default drive formatting would be APFS but try formatting it to use MAC OS Extended (Journaled) instead. Might also be worth just running the first aid tool on each of your drives.
Finally, could I get another look at your current directory structure regarding the folders the software has built.
I apologize for not having a straight solution as this is getting a little out of my area of expertise so I'm just making some educated guesses.
Thanks again for your patience :)

**Comment by hiroshclan** [comment]
it's ok :)
i'm so sorry to make you confused, maybe i missed something
this installer file after executing cmd "wget https://github.com/relf108/OSX-KVM-installer/releases/download/1.0.3/osx_kvm_installer"
![Screenshot from 2021-01-15 13-40-24](https://user-images.githubusercontent.com/44330930/104690830-b8ca1000-5737-11eb-99dc-64a8f166d91e.png)

this OSX-KVM-installer
![Screenshot from 2021-01-15 13-40-35](https://user-images.githubusercontent.com/44330930/104690980-fe86d880-5737-11eb-86f0-6d3e74ece236.png)

inside OSX-KVM-installer's folder
![Screenshot from 2021-01-15 13-40-46](https://user-images.githubusercontent.com/44330930/104691009-0d6d8b00-5738-11eb-97c0-f9caa01ab000.png)

inside OSX-KVM's folder
![Screenshot from 2021-01-15 13-41-01](https://user-images.githubusercontent.com/44330930/104691057-2118f180-5738-11eb-8c46-f133f43a9f4c.png)

inside OSX-KVM-runner's folder
![Screenshot from 2021-01-15 13-41-28](https://user-images.githubusercontent.com/44330930/104691182-56bdda80-5738-11eb-9163-b9f5a31aba5b.png)

**Comment by hiroshclan** [comment]
maybe i must repeat from the start and re-install it to make sure about the partition

**Comment by relf108** [comment]
That sounds like a good idea. From what I can see this all looks right and you're definitely using the correct command so a re-install should be your best bet.
The only thing which might be worth trying before you start again would be to just start the runner and see if it boots a successfully installed version of OSX which may be on the second root partition.

**Comment by relf108** [comment]
Assuming issue resolved due to inactivity.
